--CONSISTANCE_PARCELLE
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('Ala sy dobo');
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('Tanimboly');
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('Tanimbary');
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('Tanety');
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('');
INSERT INTO CONSISTANCE_PARCELLE (LABELLE_CONSISTANCE_PARCELLE) VALUES ('');
